In [2]:
import pandas as pd

In [3]:
comparisons = pd.read_csv('clause_comparison_table.tsv', sep='\t')

## C1

In [23]:
subset = comparisons[comparisons['exp'] == 'exp1']
subset = subset[subset['Grammaticality'] == 'ungram']
subset = subset[subset['overlaps'] == 'no']
ungram_models_exp1 = set(subset['model'].unique())

In [24]:
for model in ungram_models_exp1:
    print(model)

GODEL-large
GODEL-base
GPT-Neo-125m
Mistral-7B-v0.3
DialoGPT-medium
GPT-Neo-2.7B
DialoGPT-large
GPT2-small

## C2 Weak

In [43]:
differences = pd.read_csv('by_clause_difference_table.tsv', sep='\t')
differences = differences[differences['exp'] == 'exp2']
differences = differences[differences['Grammaticality'] == 'ungram']
differences = differences[differences['ContainsZero'] == 'no']
differences = differences.groupby(['model']).count().reset_index()[['model', 'exp']]
differences = differences[differences['exp'] == 2]
C2 = set(differences['model'].tolist())
for model in differences['model'].tolist():
    print(model)
print(len(differences['model'].tolist()))

DialoGPT-medium
DialoGPT-small
GPT-J-6B
GPT-Neo-1.3B
GPT-Neo-125m
GPT-Neo-2.7B
GPT2-XL
GPT2-large
GPT2-medium
GPT2-small
Llama-2-13B
Llama-2-13B-Chat
Llama-2-7B
Llama-2-7B-Chat
Llama-3-8B
Llama-3-8B-Instruct
Llama-3.1-8B
Llama-3.1-8B-Instruct
Mistral-7B-Instruct-v0.1
Mistral-7B-Instruct-v0.2
Mistral-7B-Instruct-v0.3
Mistral-7B-v0.1
Mistral-7B-v0.3
23

## C2 Strong

In [45]:
subset = comparisons[comparisons['exp'] == 'exp2']
subset = subset[subset['Grammaticality'] == 'ungram']
subset = subset[subset['overlaps'] == 'yes']
ungram_models_exp2 = set(subset['model'].unique())
ungram_models_exp2 = list(ungram_models_exp2)
ungram_models_exp2.sort()
for model in ungram_models_exp2: 
    if model in C2:
        print(model)

DialoGPT-medium
DialoGPT-small
GPT-Neo-1.3B
GPT-Neo-125m
GPT-Neo-2.7B
GPT2-XL
GPT2-large
GPT2-medium
GPT2-small
Llama-2-13B
Llama-2-13B-Chat
Llama-2-7B
Llama-2-7B-Chat
Llama-3-8B
Llama-3-8B-Instruct
Llama-3.1-8B
Llama-3.1-8B-Instruct
Mistral-7B-Instruct-v0.1
Mistral-7B-Instruct-v0.2

## C3

In [3]:
differences = pd.read_csv('by_clause_difference_table.tsv', sep='\t')
differences = differences[differences['exp'] != 'exp3']
differences = differences[differences['Grammaticality'] == 'gram']
differences = differences[differences['ContainsZero'] == 'yes']
differences = differences.groupby(['model']).count().reset_index()[['exp', 'model', 'count']]
#differences = differences[differences['count'] == 2]
differences

    exp                     model  count
0     1            DialoGPT-large      1
1     2            DialoGPT-small      2
2     2                GODEL-base      2
3     2               GODEL-large      2
4     3              GPT-Neo-1.3B      3
5     1              GPT-Neo-125m      1
6     3              GPT-Neo-2.7B      3
7     1                   GPT2-XL      1
8     2                GPT2-large      2
9     2               GPT2-medium      2
10    2                GPT2-small      2
11    3               Llama-2-13B      3
12    2                Llama-2-7B      2
13    2           Llama-2-7B-Chat      2
14    2                Llama-3-8B      2
15    2              Llama-3.1-8B      2
16    1     Llama-3.1-8B-Instruct      1
17    1  Mistral-7B-Instruct-v0.2      1
18    2           Mistral-7B-v0.1      2
19    2           Mistral-7B-v0.3      2

## C3 by exp

In [12]:
differences = pd.read_csv('by_clause_difference_table.tsv', sep='\t')
differences = differences[differences['exp'] == 'exp1']
differences = differences[differences['Grammaticality'] == 'gram']
differences = differences[differences['ContainsZero'] == 'yes']
differences = differences.groupby(['model']).count().reset_index()[['exp', 'model', 'count']]
differences = differences[differences['count'] == 2]
differences

    exp            model  count
1     2       GODEL-base      2
2     2      GODEL-large      2
6     2      Llama-2-13B      2
8     2       Llama-3-8B      2
9     2     Llama-3.1-8B      2
13    2  Mistral-7B-v0.3      2

In [11]:
differences = pd.read_csv('by_clause_difference_table.tsv', sep='\t')
differences = differences[differences['exp'] == 'exp2']
differences = differences[differences['Grammaticality'] == 'gram']
differences = differences[differences['ContainsZero'] == 'yes']
differences = differences.groupby(['model']).count().reset_index()[['exp', 'model', 'count']]
differences = differences[differences['count'] == 2]
differences

    exp            model  count
2     2     GPT-Neo-1.3B      2
3     2     GPT-Neo-2.7B      2
5     2       GPT2-large      2
6     2      GPT2-medium      2
7     2       GPT2-small      2
10    2  Llama-2-7B-Chat      2

## C3 by RC

In [15]:
# exp1
differences = pd.read_csv('by_clause_difference_table.tsv', sep='\t')
differences = differences[differences['exp'] == 'exp1']
differences = differences[differences['Grammaticality'] == 'gram']
differences = differences[differences['ContainsZero'] == 'yes']
differences = differences.groupby(['model', 'Clause']).count().reset_index()[['exp', 'model', 'Clause']]
differences

    exp                     model Clause
0     1            DialoGPT-small  restr
1     1                GODEL-base  appos
2     1                GODEL-base  restr
3     1               GODEL-large  appos
4     1               GODEL-large  restr
5     1              GPT-Neo-1.3B  restr
6     1              GPT-Neo-125m  restr
7     1              GPT-Neo-2.7B  restr
8     1               Llama-2-13B  appos
9     1               Llama-2-13B  restr
10    1                Llama-2-7B  appos
11    1                Llama-3-8B  appos
12    1                Llama-3-8B  restr
13    1              Llama-3.1-8B  appos
14    1              Llama-3.1-8B  restr
15    1     Llama-3.1-8B-Instruct  restr
16    1  Mistral-7B-Instruct-v0.2  restr
17    1           Mistral-7B-v0.1  restr
18    1           Mistral-7B-v0.3  appos
19    1           Mistral-7B-v0.3  restr

In [10]:
# exp2 
differences = pd.read_csv('by_clause_difference_table.tsv', sep='\t')
differences = differences[differences['exp'] == 'exp2']
differences = differences[differences['Grammaticality'] == 'gram']
differences = differences[differences['ContainsZero'] == 'yes']
differences = differences.groupby(['model', 'Clause']).count().reset_index()[['exp', 'model', 'Clause']]
differences

    exp            model Clause
0     1   DialoGPT-large  restr
1     1   DialoGPT-small  restr
2     1     GPT-Neo-1.3B  appos
3     1     GPT-Neo-1.3B  restr
4     1     GPT-Neo-2.7B  appos
5     1     GPT-Neo-2.7B  restr
6     1          GPT2-XL  appos
7     1       GPT2-large  appos
8     1       GPT2-large  restr
9     1      GPT2-medium  appos
10    1      GPT2-medium  restr
11    1       GPT2-small  appos
12    1       GPT2-small  restr
13    1      Llama-2-13B  restr
14    1       Llama-2-7B  restr
15    1  Llama-2-7B-Chat  appos
16    1  Llama-2-7B-Chat  restr
17    1  Mistral-7B-v0.1  appos

In [19]:
differences = pd.read_csv('by_clause_difference_table.tsv', sep='\t')
differences = differences[differences['exp'] == 'exp1']
differences = differences[differences['Grammaticality'] == 'gram']
differences = differences[differences['ContainsZero'] == 'yes']
differences = differences.groupby(['Clause']).count().reset_index()[['Clause', 'count']]
differences

  Clause  count
0  appos      7
1  restr     13